<form method="POST" enctype="multipart/form-data">
  <div class=" mb-3">
    <label for="title" class="form-label">
      <h2>Title</h2>
    </label>
    <input type="text" style="max-width: 1400px; margin-left : 20px; " class="form-control" name="title" id="title">
  </div>
  <div class="mb-3">
    <label for="category" class="form-label">
      <h2>Catégories</h2>
    </label>
    <select style="max-width: 1400px; margin-left : 20px; " class="form-select" id="category" name="categories[]"
      multiple>
      <?php foreach ($params["categories"] as $key => $category): ?>
      <option value="<?= $category->getId();?>"><?= $category->getName();?>
      </option>

      <?php endforeach; ?>
    </select>
  </div>
  <div class="mb-3">
    <label for="content" class="form-label">
      <h2>Contenu</h2>
    </label>
    <textarea class="form-control" style="max-width: 1400px; margin-left : 20px; " id="content" name="content"
      rows="3"></textarea>
  </div>
  <div class=" mb-3">
    <label for="image" class="form-label">
      <h2>Image</h2>
    </label>
    <input style="max-width: 1400px; margin-left : 20px; " type="file" class=" form-control" name="img" id="image">
  </div>
  <input style=" margin-left : 20px;" class="btn btn-primary" type="submit" name="value" value="Créer">
</form>