<?php 
  require_once "../src/Model/User.php";
  require_once "../src/Repository/UserRepository.php";


?>
<div class="container">
  <div class="d-block justify-content-center">
    <div>
      <?php
    require_once  dirname(__DIR__). "/Users/template_part/__add_form.phtml";
      ?>
      <!-- </div> -->
    </div>
  </div>
  <h1>Liste des utilisateurs</h1>
  <table class="table table-bordered table-dark">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Lastname</th>
        <th scope="col">Firstname</th>
        <th scope="col">Username</th>
        <th scope="col">Password</th>
      </tr>
    </thead><?php  foreach ($params['users'] as $key => $user) { ?>
    <tr>
      <th scope="row"><?php echo $user->getId()  ?></th>
      <td><?php echo $user->getLastname() ?></td>
      <td><?php echo $user->getFirstname() ?></td>
      <td><?php echo $user->getUsername() ?></td>
      <td><?php echo $user->getPassword() ?></td>

    </tr>
    <?php } ?>
    </tbody>
  </table>